# Generated by Django 4.0.4 on 2022-06-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_id', models.CharField(max_length=30)),
                ('annotation', models.IntegerField()),
                ('workflow', models.IntegerField()),
                ('user', models.IntegerField()),
                ('subject', models.IntegerField()),
            ],
        ),
    ]
