# Generated by Django 4.0.4 on 2022-09-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='classification_id',
            field=models.IntegerField(),
        ),
    ]
