# Generated by Django 4.0.4 on 2022-06-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='subject',
            new_name='subject_id',
        ),
        migrations.RenameField(
            model_name='classification',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='classification',
            old_name='workflow',
            new_name='workflow_id',
        ),
        migrations.AlterField(
            model_name='classification',
            name='classification_id',
            field=models.IntegerField(),
        ),
    ]
