# Generated by Django 4.0.4 on 2022-06-15 06:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_rename_subject_classification_subject_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='annotation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
