# Generated by Django 4.0.4 on 2022-06-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_alter_classification_annotation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classification',
        ),
    ]
