# Generated by Django 4.0.4 on 2022-06-15 06:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0004_delete_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_id', models.IntegerField()),
                ('annotation', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('workflow_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
            ],
        ),
    ]
